title: Site

tabs:
  articles:
    label: Articles
    sections:
      cas_articles:
        type: pages
        headline: CAS Articles
        parent: site.find("cas")
        template: article
        layout: table
        columns:
          title:
            label: Title
            width: 3/7
          author:
            label: Author
            type: users
            query: page.author
            text: "{{ user.name }}"
            width: 1/7
          category:
            label: Category
            text: "{{ page.category }}"
            width: 1/7
          format:
            label: Format
            text: "{{ page.format }}"
            width: 1/7
          created:
            label: Created
            type: date
            value: "{{ page.date }}"
            width: 1/7
          status:
            label: Status
            text: "{{ page.status }}"
            width: 1/7
        sortBy: date desc
        create:
          template: article
        empty: "No BAA articles yet. Create your first article!"
        search: true
        filters:
          - status
          - category
          - type

      Archive_articles:
        type: pages
        headline: Archive Entries
        parent: site.find("archive")
        template: article
        layout: table
        columns:
          title:
            label: Title
            width: 3/6
          category:
            label: Category
            text: "{{ page.category }}"
            width: 1/6
          format:
            label: Format
            text: "{{ page.format }}"
            width: 1/6
          created:
            label: Created
            type: date
            value: "{{ page.date }}"
            width: 1/6
          status:
            label: Status
            text: "{{ page.status }}"
            width: 1/6
        sortBy: date desc
        create:
          template: article
        empty: "No history articles yet. Create your first article!"
        search: true
        filters:
          - status
          - category
          - type

      gallery_articles:
        type: pages
        headline: Gallery Articles
        parent: site.find("gallery")
        template: article
        layout: table
        columns:
          title:
            label: Title
            width: 3/5
          category:
            label: Category
            text: "{{ page.category }}"
            width: 1/5
          created:
            label: Created
            type: date
            value: "{{ page.date }}"
            width: 1/5
          status:
            label: Status
            text: "{{ page.status }}"
            width: 1/5
        sortBy: date desc
        create:
          template: article
        empty: "No gallery articles yet. Create your first article!"
        search: true
        filters:
          - status
          - category

      map_articles:
        type: pages
        headline: Map Articles
        parent: site.find("map")
        template: article
        layout: table
        columns:
          title:
            label: Title
            width: 1/6
          tags:
            label: Tags
            text: "{{ page.tags }}"
            width: 3/6
          description:
            label: Description
            text: "{{ page.description }}"
            width: 1/6
          created:
            label: Created
            type: date
            value: "{{ page.date }}"
            width: 1/6
          status:
            label: Status
            text: "{{ page.status }}"
            width: 1/6
        sortBy: date desc
        create:
          template: article
        empty: "No earth articles yet. Create your first article!"
        search: true
        filters:
          - status
          - category

  pages:
    label: Pages
    sections:
      pages:
        type: pages
        query: site.children.filterBy('slug', '!=', 'map')
        headline: Pages
        layout: pages
        sortBy: num asc
        template:
          - blog
          - blocks
        create:
          - blog
          - blocks
        columns:
          title:
            label: Title
            width: 2/3
          template:
            label: Template
            text: "{{ page.intendedTemplate }}"
            width: 1/3


      tech:
        type: pages
        query: site.children.filterBy('intendedTemplate', 'not in', ['blog', 'blocks', 'article']).add(site.children.filterBy('slug', '==', 'map'))
        headline: Tech Pages
        layout: pages
        sortBy: num asc
        columns:
          title:
            label: Title
            width: 2/3
          template:
            label: Template
            text: "{{ page.intendedTemplate }}"
            width: 1/3


  media:
    label: Media
    sections:
      media_files:
        type: files
        headline: Media Library
        query: site.index.files
        layout: table
        columns:
          filename:
            label: Filename
            text: "{{ file.filename }}"
            width: 2/7
          extension:
            label: Ext
            text: "{{ file.extension }}"
            width: 1/7
          size:
            label: Size
            value: "{{ file.niceSize }}"
            width: 1/7
          parent:
            label: Parent
            value: "{{ file.parent.parents.last ?? file.parent }}"
            width: 1/7
          page:
            label: Page
            value: "{{ file.parent.title }}"
            width: 1/7
          modified:
            label: Modified
            type: date
            value: "{{ file.modified }}"
            width: 1/7
        sortBy: modified desc
        search: true
        filters:
          - extension
          - page 
          - parent

